In [ ]:
%pip install sklearn

In [1]:
from sklearn.model_selection import train_test_split

In [2]:
def dict_factory(cursor, row):
    d = {}
    for idx, col in enumerate(cursor.description):
        d[col[0]] = row[idx]
    return d

db = sqlite3.connect("/tf/face_embeddings.sqlite")
db.row_factory = dict_factory
c = db.cursor()
c.execute("SELECT * FROM face_embeddings")
rows = c.fetchall()
len(rows)

7526

In [3]:
import json
new_rows = []
for r in rows:
    r1 = r.copy()
    fe = json.loads(r["face_embeddings"])
    status = r1["status"]
    if status is None:
        continue
    r1.update(face_embeddings=fe[0] if len(fe)>0 else [], status=status)
    new_rows.append(r1)
len(new_rows)

5507

In [148]:
status_1_rows = [n for n in new_rows if n['status'] == 1]
len(status_1_rows)

459

In [149]:
status_0_rows = [n for n in new_rows if n['status'] == 0]
len(status_0_rows)

124

In [150]:
status_m1_rows = [n for n in new_rows if n['status'] == -1][:len(status_1_rows)]
len(status_m1_rows)

459

In [153]:
dataset = status_1_rows+status_0_rows+status_m1_rows

y = [r["status"] for r in dataset]
print(len(y))

1042


In [154]:
x = [r["face_embeddings"] for r in dataset]
print(len(x))

1042


In [159]:
x_train, x_test, y_train, y_test = map(np.array,train_test_split(x, y, test_size=0.25, random_state=42))

In [160]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score


In [161]:
svc = LinearSVC()
svc.fit(x_train,y_train)
acc_svc = accuracy_score(y_test, svc.predict(x_test))
acc_svc

0.685823754789272

In [162]:
test_1 = np.array([-0.08471135795116425, 0.12805385887622833, 0.07451802492141724, -0.11190157383680344, -0.08783505111932755, 0.060238923877477646, 0.002513427287340164, -0.09457127004861832, 0.25612834095954895, -0.1846698373556137, 0.18587209284305573, -0.05243683606386185, -0.28578343987464905, -0.012993558309972286, -0.03473615273833275, 0.2176039218902588, -0.21676045656204224, -0.1627623438835144, -0.06613706052303314, -0.04354097321629524, 0.015589150600135326, 0.06705089658498764, 0.018745362758636475, 0.0820474699139595, -0.03765403479337692, -0.443499892950058, -0.055465780198574066, -0.05264246463775635, -0.00932494830340147, -0.06055193766951561, -0.021135438233613968, 0.08573233336210251, -0.15701355040073395, -0.014708472415804863, 0.03031679056584835, 0.09911976009607315, -0.09898462891578674, -0.06095634400844574, 0.18161383271217346, 0.06674998253583908, -0.19221317768096924, -0.057008303701877594, 0.07913833856582642, 0.2696765959262848, 0.1559145450592041, 0.0717799961566925, -0.001589139923453331, -0.10302167385816574, 0.11635564267635345, -0.34261825680732727, 0.020499518141150475, 0.20719029009342194, 0.06118365004658699, 0.11089187115430832, 0.07381824404001236, -0.22735530138015747, 0.02908414602279663, 0.08795181661844254, -0.229806050658226, 0.11890559643507004, 0.02033146098256111, -0.16934138536453247, -0.010296964086592197, -0.056328434497117996, 0.21331650018692017, 0.11256082355976105, -0.12876924872398376, -0.1779680997133255, 0.15388093888759613, -0.17391856014728546, -0.0650663748383522, 0.031287290155887604, -0.11802505701780319, -0.23075591027736664, -0.2943381667137146, -0.029286134988069534, 0.39579471945762634, 0.20670026540756226, -0.10082265734672546, 0.0365501344203949, -0.11674435436725616, -0.06306381523609161, -0.009674659930169582, 0.17227762937545776, -0.027668531984090805, -0.05029204487800598, -0.08890112489461899, 0.004515030421316624, 0.12961480021476746, -0.04664355516433716, -0.03727509081363678, 0.2830139100551605, -0.050015293061733246, 0.0565822497010231, -0.05151905119419098, 0.0635824203491211, -0.1826668381690979, 0.03410173952579498, -0.1367577314376831, -0.08710506558418274, -0.052254438400268555, -0.09175852686166763, 0.01629367657005787, 0.08840792626142502, -0.26088616251945496, 0.1958182156085968, -0.04137430340051651, -0.016055675223469734, 0.01651957631111145, 0.0310213565826416, -0.09433948248624802, -0.0448070652782917, 0.16913899779319763, -0.28267568349838257, 0.20607632398605347, 0.2771182954311371, 0.06057044118642807, 0.2327858954668045, 0.07648297399282455, 0.09630072861909866, 0.0339510478079319, -0.07369910180568695, -0.16538415849208832, -0.0829916000366211, -0.018198097124695778, 0.011572176590561867, -0.022336330264806747, 0.06619156152009964]).reshape(1, -1)
test_2 = np.array([-0.06254289299249649, 0.013166187331080437, 0.026860956102609634, -0.006474760361015797, -0.08991967886686325, -0.06773875653743744, -0.047304630279541016, -0.13802680373191833, 0.09606793522834778, -0.12434382736682892, 0.2649054527282715, -0.024131298065185547, -0.14089615643024445, -0.06901980191469193, -0.06415656954050064, 0.12238482385873795, -0.15341021120548248, -0.11806634813547134, 0.003723437897861004, 0.01713882014155388, 0.10174981504678726, -0.0245044007897377, 0.04313648119568825, 0.09708353877067566, -0.15445207059383392, -0.2277618944644928, -0.11858876049518585, -0.13986915349960327, 0.05453192815184593, -0.04455780237913132, -0.04308818653225899, -0.04912981018424034, -0.1580248773097992, -0.0673651397228241, 0.0634053573012352, 0.030045274645090103, -0.04374757781624794, -0.06867807358503342, 0.19695939123630524, -0.02709921821951866, -0.19674797356128693, 0.06676937639713287, 0.09497177600860596, 0.28611427545547485, 0.1360950618982315, 0.09073927253484726, -0.029937744140625, -0.15164756774902344, 0.12024461477994919, -0.15849241614341736, 0.13490378856658936, 0.10416943579912186, 0.13235624134540558, 0.038801565766334534, 0.053843215107917786, -0.10583815723657608, 0.11379510164260864, 0.13619428873062134, -0.24366670846939087, 0.08083837479352951, 0.09569016098976135, 0.009695126675069332, 0.04105905443429947, -0.063237763941288, 0.22142277657985687, 0.05719294771552086, -0.11722390353679657, -0.12252005189657211, 0.13780932128429413, -0.17061027884483337, -0.08618660271167755, 0.04742414876818657, -0.13457947969436646, -0.19538111984729767, -0.28090474009513855, -0.009403450414538383, 0.39255285263061523, 0.16670773923397064, -0.1594351828098297, 0.06330730766057968, -0.03130064532160759, -0.05245257541537285, 0.08877059072256088, 0.11003189533948898, -0.0017070621252059937, -0.059278327971696854, -0.07940791547298431, -0.02705216035246849, 0.17620714008808136, -0.03999558836221695, 0.013631965965032578, 0.20955778658390045, 0.014470124617218971, -0.06588487327098846, 0.038021236658096313, 0.007965228520333767, -0.16148313879966736, 0.04643496498465538, -0.12810759246349335, -0.03224678337574005, -0.05470714345574379, -0.03641386702656746, 0.022384095937013626, 0.12514856457710266, -0.23083806037902832, 0.1307515949010849, -0.0021855062805116177, -0.06270837038755417, 0.03373250365257263, 0.02951626107096672, -0.1374160647392273, -0.08921919018030167, 0.08048249781131744, -0.24894554913043976, 0.2075740545988083, 0.13577574491500854, 0.1880837380886078, 0.09622260928153992, 0.06805764883756638, 0.04700480401515961, 0.003930267412215471, 0.014733057469129562, -0.2172318547964096, -0.04054117947816849, 0.04939669370651245, -0.11790395528078079, 0.10472768545150757, 0.03194345161318779]).reshape(1,-1)
test_3 = np.array([[-0.04531877860426903, 0.11910957843065262, 0.02730008214712143, -0.06874153017997742, -0.2279210090637207, 0.02228728123009205, -0.03803473711013794, -0.027732376009225845, 0.16611957550048828, -0.16739410161972046, 0.12425331771373749, -0.09221535921096802, -0.21558058261871338, 0.12518304586410522, -0.054481178522109985, 0.22313793003559113, -0.16142642498016357, -0.1926237940788269, -0.11156827211380005, -0.12289969623088837, 0.0345870777964592, 0.09248541295528412, 0.0046324171125888824, 0.18506811559200287, -0.09539365768432617, -0.3608402609825134, -0.02037268504500389, -0.04756578058004379, -0.06664249300956726, -0.12668846547603607, 0.032819315791130066, 0.199980229139328, -0.20728085935115814, 0.03504280000925064, 0.004909218288958073, 0.06833939254283905, -0.016963839530944824, -0.1129046231508255, 0.17248979210853577, 0.10672393441200256, -0.2545980215072632, 0.032893404364585876, 0.11489164084196091, 0.3132937252521515, 0.13826456665992737, -0.013483620248734951, 0.012758152559399605, -0.03198345750570297, 0.11021498590707779, -0.2769947648048401, 0.061680588871240616, 0.20072981715202332, 0.0381777286529541, 0.08416035026311874, 0.0638125017285347, -0.12555797398090363, 0.07546848058700562, 0.08693967759609222, -0.12831489741802216, 0.027730297297239304, 0.1065475195646286, -0.08640505373477936, 0.026699082925915718, -0.12305375188589096, 0.27067437767982483, 0.12063543498516083, -0.06107068806886673, -0.11197851598262787, 0.11799369752407074, -0.1281195878982544, -0.13593031466007233, 0.08962126076221466, -0.1779428869485855, -0.13003484904766083, -0.27330517768859863, 0.05514248460531235, 0.38909339904785156, 0.1601729393005371, -0.08841032534837723, 0.053111497312784195, 0.0005856361240148544, -0.009161390364170074, 0.008768179453909397, 0.20855528116226196, -0.05604426562786102, -0.032341938465833664, -0.04360276088118553, 0.15816989541053772, 0.20828929543495178, 0.018205633386969566, -0.07192385941743851, 0.26996612548828125, 0.03224183991551399, -0.061213258653879166, 0.0035314802080392838, 0.05377277359366417, -0.10051168501377106, -0.04015835002064705, -0.13204266130924225, -0.0014779167249798775, -0.03355812653899193, -0.0009291451424360275, -0.10572993010282516, 0.11110486090183258, -0.21245339512825012, 0.0922851637005806, -0.09715649485588074, -0.06338940560817719, -0.080438032746315, 0.05884643644094467, -0.08169346302747726, -0.023121846839785576, 0.08716195821762085, -0.21567721664905548, 0.11229341477155685, 0.13799896836280823, 0.04568042606115341, 0.11337003111839294, 0.017169330269098282, 0.08214839547872543, 0.013883762061595917, -0.0995623990893364, -0.15972773730754852, -0.0775495395064354, 0.16187366843223572, -0.010628597810864449, -0.007334533147513866, 0.04370220750570297]]).reshape(1,-1)

print(svc.decision_function(test_1))
print(svc.predict(test_1))
print(svc.decision_function(test_2))
print(svc.predict(test_2))

print(svc.decision_function(test_3))
print(svc.predict(test_3))


[[-0.09395027 -0.77109015 -0.38557054]]
[-1]
[[-0.87278555  0.73199227 -0.85386598]]
[0]
[[-0.52382936 -1.44018741  0.78150458]]
[1]


In [163]:
svc.classes_

array([-1,  0,  1])